version: '3'
services:
  redis:
    image: 'redis:latest'
  # auth:
  #   build:
  #     dockerfile: ../docker/auth.dev.Dockerfile
  #     context: ../auth
  # api:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./api
  #   volumes:
  #     - /app/node_modules
  #     - ../api:/app
  #   environment:
  #     - REDIS_HOST=redis
  # client:
  #   stdin_open: true
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./client
  #   volumes:
  #     - /app/node_modules
  #     - ../client:/app
