version: '3'
services:
  redis:
    image: 'redis:latest'
  auth:
    build:
      dockerfile: ../docker/auth.dev.Dockerfile
      context: ../auth
    ports:
      - 6000:6000
  api:
    build:
      dockerfile: ../docker/api.dev.Dockerfile
      context: ./api
    volumes:
      - /app/node_modules
      - ../api:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  # client:
  #   stdin_open: true
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./client
  #   volumes:
  #     - /app/node_modules
  #     - ../client:/app


